channels:
- conda-forge
dependencies:
- python=3.13.2
- pip<=25.0.1
- pip:
  - mlflow==2.20.3
  - cloudpickle==3.1.1
  - numpy==2.2.3
  - pandas==2.2.3
  - scikit-learn==1.6.1
  - scipy==1.15.2
  - statsmodels==0.14.4
name: mlflow-env
